import {
  type CSSProperties,
  type FormEvent,
  type ReactNode,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import ms from "milsymbol";
import {
  api,
  CLASS_LABELS,
  CLASS_SHORT,
  Capabilities,
  CurrentUser,
  classColor,
  CoalitionPolicy,
  AppLogRecord,
  ConnectInfo,
  CotLog,
  CotLogEntry,
  EudStatus,
  ConnMatrix,
  Connections,
  MsgLogEntry,
  EventStream,
  GatewayConfig,
  Health,
  MessageEvent,
  openEventStream,
  Peer,
  ServerConnection,
  ServerInput,
  SimStatus,
  Snapshot,
} from "./api";

const VOLUME_MODULES: Record<string, string> = {
  I: "security",
  II: "datamodel",
  III: "loanedradio",
  IV: "iem",
  V: "networkaccess",
};

// distinct colour per JDSS message type (drives feed border + dot)
const TYPE_COLOR: Record<string, string> = {
  Presence: "#3a78c2",
  Identification: "#8e7cc3",
  ContactSighting: "#c0392b",
  CasevacRequest: "#e08a1e",
  Chat: "#3aa76d",
  Sketch: "#4aa0a0",
  Overlay: "#a0a04a",
  GenInfo: "#5a8fbf",
  Receipt: "#6c8a6c",
  Chatrooms: "#3a9a9a",
};
const typeColor = (t?: string) => (t && TYPE_COLOR[t]) || "#7c8a99";

// Render an APP-6(D) / MIL-STD-2525D symbol from a 20-digit SIDC (carried on JDSSDM bodies).
function MilSymbol({ sidc, size = 30 }: { sidc?: string | null; size?: number }) {
  if (!sidc || sidc.length < 10) return null;
  let svg = "";
  try {
    svg = new ms.Symbol(sidc, { size }).asSVG();
  } catch {
    return null;
  }
  return <span className="milsym" title={sidc} dangerouslySetInnerHTML={{ __html: svg }} />;
}

// client-side conformance check against the reference 2525D engine
function sidcValid(sidc?: string | null): boolean {
  if (!sidc) return false;
  try {
    return new ms.Symbol(sidc).isValid() === true;
  } catch {
    return false;
  }
}

// pull the SIDC out of a message body (or its first overlay graphic)
function bodySidc(body: unknown): string | undefined {
  if (!body || typeof body !== "object") return undefined;
  const b = body as Record<string, unknown>;
  if (typeof b.sidc === "string") return b.sidc;
  const graphics = b.graphics;
  if (Array.isArray(graphics) && graphics[0] && typeof graphics[0] === "object") {
    const g = graphics[0] as Record<string, unknown>;
    if (typeof g.sidc === "string") return g.sidc;
  }
  return undefined;
}

function ClassBadge({ level }: { level: number }) {
  return (
    <span className="cbadge" style={{ background: classColor(level) }} title={CLASS_LABELS[level]}>
      {CLASS_SHORT[level] ?? "?"}
    </span>
  );
}

type Tab = "dashboard" | "config" | "connections" | "simulation" | "connect" | "logs" | "docs";
const TABS: { id: Tab; label: string }[] = [
  { id: "dashboard", label: "Dashboard" },
  { id: "config", label: "Configuration" },
  { id: "connections", label: "Connections & Policy" },
  { id: "simulation", label: "Simulation" },
  { id: "connect", label: "Connect a Client" },
  { id: "logs", label: "Logs" },
  { id: "docs", label: "Documentation" },
];

// PDF guides generated by docs/generate_docs.py and served from /docs (public/docs).
const DOCS: { file: string; title: string; blurb: string }[] = [
  {
    file: "what-is-jdss.pdf",
    title: "What is JDSS?",
    blurb:
      "The Joint Dismounted Soldier System (STANAG 4677 / AEP-76): the loaned-radio concept, " +
      "the five volumes, the JDSSDM message types, and security & classification.",
  },
  {
    file: "jdssarrow.pdf",
    title: "JDSSArrow",
    blurb:
      "This reference implementation: the pluggable architecture, volume-to-module mapping, the " +
      "web app, the simulator, coalition policy & Ed25519 signing, and the technology stack.",
  },
  {
    file: "how-to-config.pdf",
    title: "How to Configure",
    blurb:
      "The GatewayConfig model in detail: a fully annotated config file, every section, env-var " +
      "overrides, runtime edits from the UI, authority keygen, and configuring the Docker deploy.",
  },
  {
    file: "how-to-connect-clients.pdf",
    title: "How to Connect Clients (all)",
    blurb:
      "Every way to join a network: a national CLI node, the Python SDK, an ATAK / Cursor-on-Target " +
      "bridge, and the raw wire format — plus why a client may be rejected and how to verify it.",
  },
];

// Auth gate: check the session on mount, show the login screen until signed in, and fall back to
// it whenever the API reports the session as missing/expired (via the "jdss-unauthorized" event).
export function App() {
  const [user, setUser] = useState<CurrentUser | null>(null);
  const [checking, setChecking] = useState(true);

  useEffect(() => {
    api
      .me()
      .then(setUser)
      .catch(() => setUser(null))
      .finally(() => setChecking(false));
    const onUnauth = () => setUser(null);
    window.addEventListener("jdss-unauthorized", onUnauth);
    return () => window.removeEventListener("jdss-unauthorized", onUnauth);
  }, []);

  if (checking) {
    return <div className="login-screen" />;
  }
  if (!user) {
    return <Login onSuccess={setUser} />;
  }
  return (
    <Dashboard
      user={user.username}
      onLogout={() => {
        api.logout().finally(() => setUser(null));
      }}
    />
  );
}

function Login({ onSuccess }: { onSuccess: (user: CurrentUser) => void }) {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError("");
    try {
      onSuccess(await api.login(username.trim(), password));
    } catch {
      setError("Invalid username or password");
      setPassword("");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="login-screen">
      <form className="login-card" onSubmit={submit}>
        <div className="login-brand">JDSSArrow</div>
        <div className="login-sub">Coalition gateway · sign in to continue</div>
        <label className="login-field">
          <span>Username</span>
          <input
            autoFocus
            autoComplete="username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
        </label>
        <label className="login-field">
          <span>Password</span>
          <input
            type="password"
            autoComplete="current-password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </label>
        {error && <div className="login-error">{error}</div>}
        <button className="login-submit" disabled={busy || !username || !password}>
          {busy ? "Signing in…" : "Sign in"}
        </button>
      </form>
    </div>
  );
}

function Dashboard({ user, onLogout }: { user: string; onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>("dashboard");
  const [volumes, setVolumes] = useState<Record<string, string>>({});
  const [config, setConfig] = useState<GatewayConfig | null>(null);
  const [plugins, setPlugins] = useState<Record<string, string[]>>({});
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [health, setHealth] = useState<Health | null>(null);
  const [peers, setPeers] = useState<Peer[]>([]);
  const [events, setEvents] = useState<MessageEvent[]>([]);
  const wsRef = useRef<EventStream | null>(null);

  const openWs = useCallback(() => {
    wsRef.current?.close();
    const ws = openEventStream((e) => {
      if (e.direction === "sent" || e.direction === "received") {
        setEvents((prev) => [e, ...prev].slice(0, 200));
      }
    });
    wsRef.current = ws;
  }, []);

  const refreshLive = useCallback(() => {
    api.snapshot().then(setSnapshot).catch(() => {});
    api.health().then(setHealth).catch(() => {});
    api.peers().then(setPeers).catch(() => {});
  }, []);

  const reloadConfig = useCallback(() => {
    api.config().then(setConfig).catch(console.error);
    api.plugins().then(setPlugins).catch(console.error);
  }, []);

  useEffect(() => {
    api.volumes().then(setVolumes).catch(console.error);
    reloadConfig();
    refreshLive();
    openWs();
    const timer = setInterval(refreshLive, 2000);
    return () => {
      clearInterval(timer);
      wsRef.current?.close();
    };
  }, [openWs, refreshLive, reloadConfig]);

  // banner classification = highest of our own marking and anything seen on the net
  const bannerLevel = Math.max(
    config?.classification.level ?? 0,
    snapshot?.max_classification_seen ?? 0
  );

  return (
    <div className="app">
      <div className="banner" style={{ background: classColor(bannerLevel) }}>
        {CLASS_LABELS[bannerLevel]}
        {config ? ` // ${config.classification.releasable_to}` : ""}
      </div>

      <header>
        <h1>JDSSArrow</h1>
        <span className="subtitle">
          Joint Dismounted Soldier System · STANAG 4677 / AEP-76 · Web Config &amp; Monitor
        </span>
        <div className="session">
          <span className="session-user" title="signed-in operator">
            ⬢ {user}
          </span>
          <button className="logout-btn" onClick={onLogout}>
            Sign out
          </button>
        </div>
      </header>

      <nav className="tabs">
        {TABS.map((t) => (
          <button
            key={t.id}
            className={tab === t.id ? "tab active" : "tab"}
            onClick={() => setTab(t.id)}
          >
            {t.label}
          </button>
        ))}
      </nav>

      {tab === "dashboard" && (
        <>
          <KpiStrip health={health} snapshot={snapshot} config={config} peers={peers} />
          <div className="grid">
            <HealthPanel health={health} snapshot={snapshot} config={config} />
            <PeersPanel peers={peers} />
            <VolumesPanel volumes={volumes} />
            <ActionsPanel />
            <FeedPanel events={events} />
          </div>
        </>
      )}

      {tab === "config" && (
        <div className="grid">
          <ConfigPanel
            config={config}
            plugins={plugins}
            onApplied={() => {
              reloadConfig();
              refreshLive();
              openWs();
              setEvents([]);
            }}
          />
          <IdentityPanel config={config} />
          <CapabilitiesPanel />
          <EudServerPanel />
          <ServerConnectionsPanel />
          <MaintenancePanel onPurged={() => { refreshLive(); setEvents([]); }} />
        </div>
      )}

      {tab === "connections" && (
        <div className="grid">
          <ConnectionsPanel />
          <CoalitionPanel />
          <MatrixPanel />
        </div>
      )}

      {tab === "simulation" && (
        <div className="grid">
          <SimulationPanel />
        </div>
      )}

      {tab === "connect" && (
        <div className="grid">
          <ConnectPanel />
        </div>
      )}

      {tab === "logs" && (
        <div className="grid">
          <LogsPanel />
        </div>
      )}

      {tab === "docs" && (
        <div className="grid">
          <DocsPanel />
        </div>
      )}

      <div className="banner" style={{ background: classColor(bannerLevel) }}>
        {CLASS_LABELS[bannerLevel]}
      </div>
    </div>
  );
}

function KpiStrip({
  health,
  snapshot,
  config,
  peers,
}: {
  health: Health | null;
  snapshot: Snapshot | null;
  config: GatewayConfig | null;
  peers: Peer[];
}) {
  const connected = peers.filter((p) => p.connected).length;
  const msgs = snapshot
    ? Object.values(snapshot.counts_by_type).reduce((a, b) => a + b, 0)
    : 0;
  const rejected = (health?.dropped_rejected ?? 0) + (health?.dropped_by_policy ?? 0);
  const cards: { label: string; value: string; sub?: string; accent?: string }[] = [
    { label: "Status", value: health?.status?.toUpperCase() ?? "…", accent: "var(--accent)" },
    { label: "Uptime", value: health ? `${Math.round(health.uptime_s)}s` : "…" },
    { label: "Peers", value: String(connected), sub: `${peers.length} known` },
    { label: "Messages", value: String(msgs), sub: `${snapshot?.buffered ?? 0} buffered` },
    { label: "Rejected", value: String(rejected), sub: "auth/policy", accent: rejected ? "#c0392b" : undefined },
    {
      label: "Coalition",
      value: health?.coalition_version ? `v${health.coalition_version}` : "—",
      sub: health?.is_policy_authority ? "authority" : "member",
    },
    {
      label: "Classification",
      value: config ? CLASS_SHORT[config.classification.level] : "…",
      accent: config ? classColor(config.classification.level) : undefined,
    },
  ];
  return (
    <div className="kpis">
      {cards.map((c) => (
        <div className="kpi" key={c.label}>
          <div className="kpi-value" style={{ color: c.accent ?? "var(--text)" }}>
            {c.value}
          </div>
          <div className="kpi-label">{c.label}</div>
          {c.sub && <div className="kpi-sub">{c.sub}</div>}
        </div>
      ))}
    </div>
  );
}

function CapabilitiesPanel() {
  const [caps, setCaps] = useState<Capabilities | null>(null);
  const [saved, setSaved] = useState<string>("");
  const load = () => api.capabilities().then(setCaps).catch(console.error);
  useEffect(() => {
    load();
  }, []);
  if (!caps) return <section className="card">Loading capabilities…</section>;

  const toggle = async (t: string, dir: "receive" | "emit", cur: boolean) => {
    const res = await api.setCapability(t, dir, !cur);
    const body = await res.json();
    setSaved(body.persisted ? "✓ saved to config file" : "applied live (no config file to persist)");
    load();
  };

  return (
    <section className="card caps">
      <h2>Capability Matrix (permissions)</h2>
      <p className="hint">
        On/off per JDSS message type. <b>RX</b> = accept inbound (else dropped on ingest);{" "}
        <b>TX</b> = allowed to originate. Applied live &amp; persisted to the config file.{" "}
        {saved && <span style={{ color: "var(--accent)" }}>{saved}</span>}
      </p>
      <table className="capgrid">
        <thead>
          <tr>
            <th>Message type</th>
            <th>RX (receive)</th>
            <th>TX (emit)</th>
          </tr>
        </thead>
        <tbody>
          {caps.types.map((t) => (
            <tr key={t}>
              <td>{t}</td>
              <td>
                <input
                  type="checkbox"
                  checked={caps.receive[t]}
                  onChange={() => toggle(t, "receive", caps.receive[t])}
                />
              </td>
              <td>
                <input
                  type="checkbox"
                  checked={caps.emit[t]}
                  onChange={() => toggle(t, "emit", caps.emit[t])}
                />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}

function IdentityPanel({ config }: { config: GatewayConfig | null }) {
  if (!config) return <section className="card">…</section>;
  const rows: [string, string][] = [
    ["Node id", config.identity.node_id],
    ["Callsign", config.identity.callsign],
    ["Unit", config.identity.unit],
    ["Nation", config.identity.nation],
    ["Role", config.identity.role],
    ["Network", config.network.network_id],
    ["Multicast", `${config.network.multicast_group ?? "(derived)"}:${config.network.multicast_port ?? ""}`],
  ];
  return (
    <section className="card">
      <h2>Node Identity &amp; Network</h2>
      <table className="kv">
        <tbody>
          {rows.map(([k, v]) => (
            <tr key={k}>
              <td>{k}</td>
              <td>{v}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}

function VolumesPanel({ volumes }: { volumes: Record<string, string> }) {
  return (
    <section className="card">
      <h2>AEP-76 Volumes</h2>
      <ul className="volumes">
        {Object.entries(volumes).map(([vol, subject]) => (
          <li key={vol}>
            <span className="badge">Vol {vol}</span> {subject}
            <code>jdssarrow.{VOLUME_MODULES[vol]}</code>
          </li>
        ))}
      </ul>
    </section>
  );
}

function ConfigPanel({
  config,
  plugins,
  onApplied,
}: {
  config: GatewayConfig | null;
  plugins: Record<string, string[]>;
  onApplied: () => void;
}) {
  const [draft, setDraft] = useState<GatewayConfig | null>(null);
  const [status, setStatus] = useState<string>("");
  useEffect(() => setDraft(config), [config]);
  if (!draft) return <section className="card">Loading config…</section>;

  const setPlugin = (k: keyof GatewayConfig["plugins"], v: string) =>
    setDraft({ ...draft, plugins: { ...draft.plugins, [k]: v } });

  const rows: [string, keyof GatewayConfig["plugins"], string][] = [
    ["Codec (Vol II)", "codec", "codecs"],
    ["Transport (Vol IV)", "transport", "transports"],
    ["Security (Vol I)", "security", "security"],
    ["Bearer (Vol III)", "bearer", "bearers"],
    ["Allocator (Vol V)", "allocator", "allocators"],
  ];

  const apply = async () => {
    setStatus("applying…");
    try {
      await api.updateConfig({
        plugins: draft.plugins,
        network: { repeat: draft.network.repeat },
        classification: draft.classification,
      });
      setStatus("applied ✓ gateway restarted");
      onApplied();
    } catch (e) {
      setStatus(String(e));
    }
  };

  return (
    <section className="card">
      <h2>Pluggable Configuration</h2>
      <table>
        <tbody>
          {rows.map(([label, key, group]) => (
            <tr key={key}>
              <td>{label}</td>
              <td>
                <select value={draft.plugins[key]} onChange={(e) => setPlugin(key, e.target.value)}>
                  {(plugins[group] ?? [draft.plugins[key]]).map((name) => (
                    <option key={name} value={name}>
                      {name}
                    </option>
                  ))}
                </select>
              </td>
            </tr>
          ))}
          <tr>
            <td>Repeat (reliability)</td>
            <td>
              <input
                type="number"
                min={1}
                max={8}
                value={draft.network.repeat}
                onChange={(e) =>
                  setDraft({
                    ...draft,
                    network: { ...draft.network, repeat: Number(e.target.value) },
                  })
                }
              />
            </td>
          </tr>
          <tr>
            <td>Classification</td>
            <td>
              <select
                value={draft.classification.level}
                onChange={(e) =>
                  setDraft({
                    ...draft,
                    classification: { ...draft.classification, level: Number(e.target.value) },
                  })
                }
              >
                {[0, 1, 2, 3].map((l) => (
                  <option key={l} value={l}>
                    {CLASS_LABELS[l]}
                  </option>
                ))}
              </select>
            </td>
          </tr>
          <tr>
            <td>Releasable to</td>
            <td>
              <input
                value={draft.classification.releasable_to}
                onChange={(e) =>
                  setDraft({
                    ...draft,
                    classification: { ...draft.classification, releasable_to: e.target.value },
                  })
                }
              />
            </td>
          </tr>
        </tbody>
      </table>
      <button onClick={apply}>Apply &amp; restart gateway</button>
      <span className="status">{status}</span>
      <p className="hint">
        Every seam is a runtime plugin (values from <code>/api/plugins</code>). Applying hot-restarts
        the gateway on the new selection.
      </p>
    </section>
  );
}

function HealthPanel({
  health,
  snapshot,
  config,
}: {
  health: Health | null;
  snapshot: Snapshot | null;
  config: GatewayConfig | null;
}) {
  return (
    <section className="card">
      <h2>System Health &amp; Monitor</h2>
      {!health ? (
        "…"
      ) : (
        <>
          <p>
            <span className={`dot ${health.engine_running ? "up" : "down"}`} />
            <strong>{health.status.toUpperCase()}</strong> · {config?.identity.callsign} (
            {health.node_id}) · net <strong>{config?.network.network_id}</strong>
          </p>
          <table className="kv">
            <tbody>
              <tr><td>Uptime</td><td>{health.uptime_s}s</td></tr>
              <tr><td>Engine</td><td>{health.engine_running ? "running" : "stopped"}</td></tr>
              <tr><td>OS threads</td><td>{health.threads}</td></tr>
              <tr><td>asyncio tasks</td><td>{health.asyncio_tasks}</td></tr>
              <tr><td>WS subscribers</td><td>{health.ws_subscribers}</td></tr>
              <tr><td>Telemetry buffered</td><td>{health.telemetry_buffered}</td></tr>
              <tr>
                <td>Active stack</td>
                <td>
                  {health.codec}/{health.transport}/{health.security} ×{health.repeat}
                </td>
              </tr>
            </tbody>
          </table>
          <div className="counts">
            {snapshot &&
              Object.entries(snapshot.counts_by_type).map(([t, c]) => (
                <span key={t} className="chip" style={{ borderColor: typeColor(t) }}>
                  {t} <strong>{c}</strong>
                </span>
              ))}
          </div>
        </>
      )}
    </section>
  );
}

function PeersPanel({ peers }: { peers: Peer[] }) {
  const [selected, setSelected] = useState<Peer | null>(null);
  return (
    <section className="card">
      <h2>Connected Peers ({peers.filter((p) => p.connected).length})</h2>
      {peers.length === 0 ? (
        <p className="hint">No peers seen yet.</p>
      ) : (
        <table className="peers">
          <thead>
            <tr>
              <th></th>
              <th>Callsign</th>
              <th>Nation</th>
              <th>Role</th>
              <th>Class</th>
              <th>Msgs</th>
              <th>Seen</th>
            </tr>
          </thead>
          <tbody>
            {peers.map((p) => (
              <tr
                key={p.node_id}
                className={`clickable ${p.connected ? "" : "stale"}`}
                title="click for peer details"
                onClick={() => setSelected(p)}
              >
                <td>
                  <span className={`dot ${p.connected ? "up" : "down"}`} />
                </td>
                <td>{p.callsign ?? p.node_id}</td>
                <td>{p.nation ?? "—"}</td>
                <td>{p.role ?? "—"}</td>
                <td>
                  <ClassBadge level={p.classification} />
                </td>
                <td>{p.messages}</td>
                <td>{p.seconds_ago}s</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      {selected && <PeerModal peer={selected} onClose={() => setSelected(null)} />}
    </section>
  );
}

function ActionsPanel() {
  const [text, setText] = useState("SITREP: all quiet");
  return (
    <section className="card">
      <h2>Inject (Web → Network)</h2>
      <div className="row">
        <input value={text} onChange={(e) => setText(e.target.value)} />
        <button onClick={() => api.publishChat(text)}>Send chat</button>
      </div>
      <button onClick={() => api.publishContact(50.851, 4.352, "Web-reported contact")}>
        Report contact
      </button>
    </section>
  );
}

function CodeBlock({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard unavailable */
    }
  };
  return (
    <div className="code">
      <button className="copy" onClick={copy}>
        {copied ? "copied ✓" : "copy"}
      </button>
      <pre>{code}</pre>
    </div>
  );
}

function ConnectPanel() {
  const [info, setInfo] = useState<ConnectInfo | null>(null);
  const [reveal, setReveal] = useState(false);
  useEffect(() => {
    api.connect().then(setInfo).catch(console.error);
  }, []);
  if (!info) return <section className="card">Loading connection info…</section>;

  // the coalition PSK is a shared secret — masked until explicitly revealed
  const psk = reveal ? info.psk : "‹reveal PSK above›";

  const yamlCfg = `# node-x.yaml — a new client joining this JDSS network
identity:
  node_id: node-x
  callsign: XRAY-9
  nation: XXX
  role: rifleman
plugins:
  codec: ${info.codec}
  transport: udp
  security: ${info.security}
network:
  network_id: ${info.network_id}
  psk: ${psk}          # coalition shared key — must match
  repeat: ${info.repeat}${
    info.policy_authority
      ? `
connections:
  policy_authority: ${info.policy_authority}
  authority_public_key: ${info.authority_public_key ?? "<authority Ed25519 pubkey>"}`
      : ""
  }`;

  const cli = `# install, then run the node — it joins ${info.multicast_group}:${info.port}
uv pip install -e ".[dev]"
jdssarrow run --config node-x.yaml --casevac`;

  const py = `import asyncio
from jdssarrow.config.models import GatewayConfig, NodeIdentity, PluginSelection, NetworkConfig
from jdssarrow.gateway.gateway import JdssGateway
from jdssarrow.gateway.node import SoldierNode

cfg = GatewayConfig(
    identity=NodeIdentity(node_id="node-x", callsign="XRAY-9"),
    plugins=PluginSelection(codec="${info.codec}", transport="udp", security="${info.security}"),
    network=NetworkConfig(network_id="${info.network_id}", psk="${psk}"),
)

async def main():
    node = SoldierNode(JdssGateway(cfg))
    await node.start()
    await node.identify()
    await node.presence(50.85, 4.35, battery_pct=90)   # appears on every peer's COP
    await node.report_contact(50.86, 4.36, "dismounted patrol")
    await asyncio.sleep(2)
    await node.stop()

asyncio.run(main())`;

  const atak = `ATAK / external EUD (Cursor-on-Target) — via a bridge

ATAK speaks CoT XML over the TAK protocol, not JDSSDM. To bring an ATAK EUD onto this
network, run a small CoT <-> JDSS bridge that joins the multicast group and maps:

  CoT event (a-f-G-U-C…)  ->  Presence / ContactSighting   (with APP-6(D) SIDC)
  CoT chat (GeoChat)      ->  Chat
  CoT markers / drawings  ->  Overlay graphics
  CoT medevac (9-line)    ->  CasevacRequest

Join coordinates for the bridge:
  group:    ${info.multicast_group}:${info.port}
  codec:    ${info.codec}   (${info.codec_content_type})
  security: ${info.security}  (HMAC-SHA256 over the payload, key = coalition PSK)
  network:  ${info.network_id}

(No ATAK bridge is bundled — this is the integration contract to implement one.)`;

  const raw = `Any language — raw wire format (implement the frame + auth):

  frame = "${info.frame.magic}"(4) | version=${info.frame.version}(1)
        | codec-name | security-name | length(4, big-endian) | payload
  payload = ${info.frame.payload}

  1. build a JDSSDM message (header + typed body) and encode with the "${info.codec}" codec
  2. append/verify HMAC-SHA256(payload, key="${psk}")   [security="${info.security}"]
  3. send the frame to UDP multicast ${info.multicast_group}:${info.port} (send it ${info.repeat}x for reliability)
  4. receivers dedup by (originator_id, message_id)

Message types on this network: ${info.message_types.join(", ")}`;

  return (
    <section className="card connect">
      <h2>Connect a Client to this JDSS Network</h2>
      <table className="kv joinparams">
        <tbody>
          <tr><td>Network</td><td>{info.network_id}</td></tr>
          <tr><td>Multicast</td><td>{info.multicast_group}:{info.port}</td></tr>
          <tr><td>Codec (Vol II)</td><td>{info.codec} <span className="hint">({info.codec_content_type})</span></td></tr>
          <tr><td>Security (Vol I)</td><td>{info.security} — HMAC-SHA256, key = coalition PSK</td></tr>
          <tr>
            <td>Coalition PSK</td>
            <td>
              <code>{reveal ? info.psk : "•".repeat(Math.min(12, info.psk.length))}</code>{" "}
              <button className="reveal-btn" onClick={() => setReveal((r) => !r)}>
                {reveal ? "hide" : "reveal"}
              </button>
              {!reveal && <span className="hint"> shared secret</span>}
            </td>
          </tr>
          <tr><td>Policy authority</td><td>{info.policy_authority ?? "—"}</td></tr>
        </tbody>
      </table>
      <p className="hint">
        The coalition PSK is a shared secret — masked by default. <b>Reveal</b> it to copy
        working snippets (they show <code>‹reveal PSK above›</code> until then).
      </p>

      <h3>① National soldier system / CLI node</h3>
      <p className="hint">Drop this config and run the bundled node — joins over real UDP multicast.</p>
      <CodeBlock code={yamlCfg} />
      <CodeBlock code={cli} />

      <h3>② Custom client — Python SDK</h3>
      <CodeBlock code={py} />

      <h3>③ ATAK / external EUD (Cursor-on-Target)</h3>
      <CodeBlock code={atak} />

      <h3>④ Any language — raw wire</h3>
      <CodeBlock code={raw} />
    </section>
  );
}

function CotTrafficModal({
  title,
  fetcher,
  onClose,
}: {
  title: string;
  fetcher: () => Promise<CotLog>;
  onClose: () => void;
}) {
  const [log, setLog] = useState<CotLog | null>(null);
  const [sel, setSel] = useState<CotLogEntry | null>(null);
  useEffect(() => {
    const load = () => fetcher().then(setLog).catch(() => {});
    load();
    const t = setInterval(load, 1500);
    return () => clearInterval(t);
  }, [fetcher]);
  const hhmmss = (ts: number) => new Date(ts * 1000).toISOString().slice(11, 19);
  return (
    <Modal title={title} onClose={onClose}>
      <p className="hint">
        Live CoT crossing the bridge — <b>▲ out</b> = JDSS→CoT sent to the server,{" "}
        <b>▼ in</b> = CoT→JDSS received. {log ? `${log.counts.out ?? 0} out · ${log.counts.in ?? 0} in` : ""}.
        Click a row for the raw CoT.
      </p>
      <p className="hint">
        Note: under a containerized deploy the <b>peer</b> shows the Docker bridge/host address
        (e.g. <code>172.18.0.1</code>), not the client's real IP — Docker NATs published-port
        connections. Run the gateway natively (or <code>--network host</code>) to see real client
        IPs. Identify the device by its CoT uid / callsign.
      </p>
      <div className="cotlog">
        <div className="cotlog-head">
          <span></span>
          <span>Type</span>
          <span>uid / callsign</span>
          <span>peer</span>
          <span>time</span>
        </div>
        <ul>
          {(log?.entries ?? []).slice().reverse().map((e, i) => (
            <li key={i} className={`${e.direction} clickable`} onClick={() => setSel(e)}>
              <span className="dir">{e.direction === "out" ? "▲" : "▼"}</span>
              <span className="type" style={{ color: typeColor(cotToJdss(e.type)) }}>
                {e.type ?? "—"}
              </span>
              <span className="from">
                {e.callsign ? `${e.callsign} ` : ""}
                {e.uid ?? ""}
              </span>
              <span className="hint">{e.peer}</span>
              <span className="time">{hhmmss(e.ts)}</span>
            </li>
          ))}
          {log && log.entries.length === 0 && <li className="hint">no CoT yet</li>}
        </ul>
      </div>
      {sel && (
        <>
          <h3>
            Raw CoT · {sel.type} ({sel.size} bytes)
          </h3>
          <div className="code">
            <button
              className="copy"
              onClick={() => navigator.clipboard?.writeText(sel.raw)}
            >
              copy
            </button>
            <pre>{prettyXml(sel.raw)}</pre>
          </div>
        </>
      )}
    </Modal>
  );
}

// map a CoT type back to the JDSS type name so the colour matches the rest of the UI
function cotToJdss(t: string | null): string {
  if (!t) return "";
  if (t.startsWith("a-f")) return "Presence";
  if (t.startsWith("a-")) return "ContactSighting";
  if (t.startsWith("b-t-f")) return "Chat";
  if (t.startsWith("b-r-f-h-c")) return "CasevacRequest";
  if (t.startsWith("u-d") || t.startsWith("b-m-p")) return "Overlay";
  return "";
}

// light-touch pretty printer: newline before each nested tag so raw CoT is readable
function prettyXml(xml: string): string {
  return xml.replace(/></g, ">\n<");
}

function MaintenancePanel({ onPurged }: { onPurged: () => void }) {
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState("");

  const purge = async () => {
    if (!confirm("Delete ALL messages — audit log, telemetry cache, dedup cache and CoT traffic logs? This cannot be undone.")) {
      return;
    }
    setBusy(true);
    setMsg("purging…");
    try {
      const r = await api.purge();
      const parts = Object.entries(r.cleared)
        .filter(([, n]) => n > 0)
        .map(([k, n]) => `${n} ${k.replace(/_/g, " ")}`);
      setMsg(`✓ cleared ${r.total} message${r.total === 1 ? "" : "s"}${parts.length ? ` (${parts.join(", ")})` : ""}`);
      onPurged();
    } catch (e) {
      setMsg(String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="card">
      <h2>Maintenance</h2>
      <p className="hint">
        Delete all buffered/logged messages on this node: the message audit log, the telemetry
        cache, the receive dedup cache, and the CoT server/EUD traffic logs. Peers, the application
        log and Prometheus counters are kept.
      </p>
      <button className="danger" onClick={purge} disabled={busy}>
        Clear all messages
      </button>
      <span className="status">{msg}</span>
    </section>
  );
}

function EudServerPanel() {
  const [st, setSt] = useState<EudStatus | null>(null);
  const [port, setPort] = useState(8087);
  const [advertised, setAdvertised] = useState("");
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState("");
  const [showTraffic, setShowTraffic] = useState(false);

  const load = useCallback(() => {
    api
      .eud()
      .then((s) => {
        setSt(s);
        setPort(s.port);
        setAdvertised(s.advertised_host ?? "");
      })
      .catch((e) => setMsg(String(e)));
  }, []);

  useEffect(() => {
    load();
    const t = setInterval(() => api.eud().then(setSt).catch(() => {}), 2500);
    return () => clearInterval(t);
  }, [load]);

  if (!st) return <section className="card">Loading ATAK server…</section>;

  // The address ATAK should use: an explicit advertised host wins; otherwise fall back to the
  // hostname this dashboard was opened with (reachable by construction), not the container IP.
  const displayHost = (advertised || st.advertised_host || location.hostname || st.lan_ip).trim();

  const apply = async (enabled: boolean) => {
    setBusy(true);
    setMsg("");
    try {
      const s = await api.setEud({ enabled, port, advertised_host: advertised.trim() || null });
      setSt(s);
      setMsg(enabled ? (s.listening ? "listening ✓" : "failed to bind") : "stopped");
    } catch (e) {
      setMsg(String(e));
    } finally {
      setBusy(false);
    }
  };

  const saveAdvertised = async () => {
    setBusy(true);
    setMsg("");
    try {
      const s = await api.setEud({
        enabled: st.enabled,
        port: st.port,
        advertised_host: advertised.trim() || null,
      });
      setSt(s);
      setMsg("advertised address saved ✓");
    } catch (e) {
      setMsg(String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="card eud">
      <h2>Serve ATAK / EUDs (built-in TAK server)</h2>
      <p className="hint">
        Let ATAK / WinTAK / iTAK devices connect <b>directly to this node</b> — no separate TAK
        server. Their tracks join the coalition COP and coalition traffic streams to them as CoT.
      </p>

      <div className="eud-status">
        <span className={`dot ${st.listening ? "up" : "down"}`} />
        <b>{st.listening ? "LISTENING" : st.enabled ? "ENABLED (bind failed)" : "off"}</b>
        {st.listening && (
          <span className="hint">
            {" "}· {st.client_count} EUD{st.client_count === 1 ? "" : "s"} connected
          </span>
        )}
        {st.last_error && !st.listening && <span className="srv-err"> {st.last_error}</span>}
      </div>

      <div className="eud-controls">
        <label>
          Port{" "}
          <input
            type="number"
            min={1}
            max={65535}
            value={port}
            disabled={st.listening}
            onChange={(e) => setPort(Number(e.target.value))}
          />
        </label>
        {st.enabled ? (
          <button className="danger" disabled={busy} onClick={() => apply(false)}>
            Stop
          </button>
        ) : (
          <button disabled={busy} onClick={() => apply(true)}>
            Start server
          </button>
        )}
        <button className="ghost" onClick={() => setShowTraffic(true)}>
          CoT traffic
        </button>
        <span className="status">{msg}</span>
      </div>
      {showTraffic && (
        <CotTrafficModal
          title="ATAK / EUD CoT traffic"
          fetcher={() => api.eudTraffic()}
          onClose={() => setShowTraffic(false)}
        />
      )}

      <div className="eud-advertise">
        <label>
          Advertised host (what ATAK connects to)
          <input
            value={advertised}
            onChange={(e) => setAdvertised(e.target.value)}
            placeholder={`public/LAN IP or DNS — auto-detected: ${st.lan_ip}`}
          />
        </label>
        <button className="ghost" onClick={saveAdvertised} disabled={busy}>
          Save address
        </button>
      </div>
      <p className="hint">
        Under Docker/NAT the auto-detected IP is the container's internal address ({st.lan_ip}) —
        set your host's LAN IP or public IP/DNS here, and make sure port <b>{st.port}</b> is
        published from the container and open on your firewall.
      </p>

      {st.listening && (
        <div className="eud-howto">
          <p className="hint">
            In ATAK: <b>Settings → Network Preferences → Network Connections → TAK Servers → +</b> and
            add (TCP, no SSL):
          </p>
          <CodeBlock code={`${displayHost}:${st.port}`} />
          {st.clients.length > 0 && (
            <table className="kv">
              <tbody>
                {st.clients.map((c) => (
                  <tr key={c}>
                    <td>
                      <span className="dot up" /> EUD
                    </td>
                    <td>
                      <code>{c}</code>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
    </section>
  );
}

const BLANK_SERVER: ServerInput = {
  name: "",
  host: "",
  port: 8089,
  tls: false,
  verify: true,
  client_cert: null,
  client_key: null,
  cacert: null,
  enabled: true,
};

const SERVER_STATE_COLOR: Record<string, string> = {
  connected: "#3aa76d",
  connecting: "#d29a2b",
  disabled: "#7c8a99",
  stopped: "#c0392b",
};

// read a File's bytes as base64 (for uploading a .p12 as JSON, no multipart)
function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onerror = () => reject(new Error("could not read file"));
    r.onload = () => {
      const res = r.result as string; // "data:...;base64,XXXX"
      resolve(res.slice(res.indexOf(",") + 1));
    };
    r.readAsDataURL(file);
  });
}

function ServerConnectionsPanel() {
  const [servers, setServers] = useState<ServerConnection[]>([]);
  const [draft, setDraft] = useState<ServerInput>(BLANK_SERVER);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState("");
  const [traffic, setTraffic] = useState<string | null>(null); // server id, or "*" for all
  const [p12File, setP12File] = useState<File | null>(null);
  const [p12Pass, setP12Pass] = useState("");
  const [p12Msg, setP12Msg] = useState("");

  const load = useCallback(() => {
    api
      .servers()
      .then((r) => setServers(r.servers))
      .catch((e) => setStatus(String(e)));
  }, []);

  useEffect(() => {
    load();
    const t = setInterval(load, 2500); // live connection status
    return () => clearInterval(t);
  }, [load]);

  const set = <K extends keyof ServerInput>(k: K, v: ServerInput[K]) =>
    setDraft((d) => ({ ...d, [k]: v }));

  const resetP12 = () => {
    setP12File(null);
    setP12Pass("");
    setP12Msg("");
  };

  const reset = () => {
    setDraft(BLANK_SERVER);
    setEditingId(null);
    setStatus("");
    resetP12();
  };

  const importP12 = async () => {
    if (!p12File) return;
    setBusy(true);
    setP12Msg("importing…");
    try {
      const b64 = await fileToBase64(p12File);
      const r = await api.importPkcs12(b64, p12Pass);
      setDraft((d) => ({
        ...d,
        tls: true,
        client_cert: r.client_cert,
        client_key: r.client_key,
        cacert: r.cacert,
      }));
      setP12Msg(`✓ imported cert${r.common_name ? ` — CN=${r.common_name}` : ""}${r.cacert ? " (+CA)" : ""}`);
    } catch (e) {
      setP12Msg(`✗ ${String(e).replace(/^Error:\s*/, "")}`);
    } finally {
      setBusy(false);
    }
  };

  const edit = (s: ServerConnection) => {
    setEditingId(s.id);
    setStatus("");
    resetP12();
    setDraft({
      name: s.name,
      host: s.host,
      port: s.port,
      tls: s.tls,
      verify: s.verify,
      client_cert: s.client_cert,
      client_key: s.client_key,
      cacert: s.cacert,
      enabled: s.enabled,
    });
  };

  const save = async () => {
    if (!draft.host) {
      setStatus("host is required");
      return;
    }
    setBusy(true);
    try {
      const r = editingId
        ? await api.updateServer(editingId, draft)
        : await api.createServer(draft);
      setServers(r.servers);
      setStatus(editingId ? "updated ✓" : "added ✓");
      reset();
    } catch (e) {
      setStatus(String(e));
    } finally {
      setBusy(false);
    }
  };

  const remove = async (s: ServerConnection) => {
    if (!confirm(`Delete server "${s.name || s.host}"?`)) return;
    setBusy(true);
    try {
      const r = await api.deleteServer(s.id);
      setServers(r.servers);
      if (editingId === s.id) reset();
    } catch (e) {
      setStatus(String(e));
    } finally {
      setBusy(false);
    }
  };

  const toggle = async (s: ServerConnection) => {
    setBusy(true);
    try {
      const r = await api.updateServer(s.id, { ...s, enabled: !s.enabled });
      setServers(r.servers);
    } catch (e) {
      setStatus(String(e));
    } finally {
      setBusy(false);
    }
  };

  const test = async () => {
    setBusy(true);
    setStatus("testing…");
    try {
      const r = await api.testServer(draft);
      setStatus(r.ok ? `✓ ${r.detail}` : `✗ ${r.detail}`);
    } catch (e) {
      setStatus(String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="card servers">
      <h2>CoT / TAK Server Connections</h2>
      <p className="hint">
        Bridge this node to OpenTAKServer / TAK Server / FreeTAKServer. Enabled connections relay
        coalition JDSS traffic out as CoT and inbound CoT back onto the network. Changes are applied
        live and saved to the config file. <b>OpenTAKServer</b>: 8088 (plaintext) or 8089 (TLS,
        client cert whose CN is a registered OTS user).
      </p>
      <button className="ghost" onClick={() => setTraffic("*")}>
        Show CoT traffic (all servers)
      </button>

      {servers.length === 0 ? (
        <p className="hint">No server connections yet — add one below.</p>
      ) : (
        <table className="srvtable">
          <thead>
            <tr>
              <th></th>
              <th>Name</th>
              <th>Endpoint</th>
              <th>Status</th>
              <th>Link</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {servers.map((s) => (
              <tr key={s.id} className={s.enabled ? "" : "disabled"}>
                <td>
                  <span
                    className="dot"
                    style={{ background: SERVER_STATE_COLOR[s.state] ?? "#7c8a99" }}
                    title={s.state}
                  />
                </td>
                <td>
                  {s.name || s.id}
                  {s.tls && <span className="tlsbadge">TLS</span>}
                </td>
                <td>
                  <code>
                    {s.host}:{s.port}
                  </code>
                </td>
                <td>
                  <span style={{ color: SERVER_STATE_COLOR[s.state] ?? "var(--muted)" }}>
                    {s.state}
                  </span>
                  {s.last_error && !s.connected && (
                    <div className="srv-err" title={s.last_error}>
                      {s.last_error.slice(0, 40)}
                    </div>
                  )}
                </td>
                <td className="hint">
                  {s.connects > 0 ? `${s.connects} conn` : "—"}
                  {s.reconnects > 0 ? ` · ${s.reconnects} re` : ""}
                  {s.queued > 0 ? ` · ${s.queued} q` : ""}
                </td>
                <td className="srv-actions">
                  <button onClick={() => setTraffic(s.id)}>Traffic</button>
                  <button onClick={() => edit(s)}>Edit</button>
                  <button onClick={() => toggle(s)} disabled={busy}>
                    {s.enabled ? "Disable" : "Enable"}
                  </button>
                  <button className="danger" onClick={() => remove(s)} disabled={busy}>
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <h3>{editingId ? `Edit "${editingId}"` : "Add a server"}</h3>
      <div className="srvform">
        <label>
          Name
          <input value={draft.name} onChange={(e) => set("name", e.target.value)} placeholder="OpenTAKServer" />
        </label>
        <div className="srvrow">
          <label style={{ flex: 2 }}>
            Host
            <input value={draft.host} onChange={(e) => set("host", e.target.value)} placeholder="192.168.0.202" />
          </label>
          <label style={{ flex: 1 }}>
            Port
            <input
              type="number"
              min={1}
              max={65535}
              value={draft.port}
              onChange={(e) => set("port", Number(e.target.value))}
            />
          </label>
        </div>
        <div className="srvchecks">
          <label className="inline">
            <input type="checkbox" checked={draft.tls} onChange={(e) => set("tls", e.target.checked)} /> TLS
          </label>
          <label className="inline">
            <input
              type="checkbox"
              checked={draft.verify}
              disabled={!draft.tls}
              onChange={(e) => set("verify", e.target.checked)}
            />{" "}
            verify server cert
          </label>
          <label className="inline">
            <input type="checkbox" checked={draft.enabled} onChange={(e) => set("enabled", e.target.checked)} /> enabled
          </label>
        </div>
        {draft.tls && (
          <div className="srvcerts">
            <p className="hint">
              Import a <b>.p12 / .pfx</b> (client certificate + key, and the CA). Its CommonName
              must be a registered OpenTAKServer user. Nothing is stored until you save the server.
            </p>
            <div className="p12row">
              <input
                type="file"
                accept=".p12,.pfx,application/x-pkcs12"
                onChange={(e) => {
                  setP12File(e.target.files?.[0] ?? null);
                  setP12Msg("");
                }}
              />
              <input
                type="password"
                placeholder=".p12 password"
                value={p12Pass}
                onChange={(e) => setP12Pass(e.target.value)}
              />
              <button className="ghost" type="button" onClick={importP12} disabled={!p12File || busy}>
                Import .p12
              </button>
            </div>
            {draft.client_cert && (
              <p className="hint" style={{ color: "var(--accent)" }}>
                ✓ certificate loaded{draft.cacert ? " (+CA)" : ""}
              </p>
            )}
            {p12Msg && <p className="hint">{p12Msg}</p>}
          </div>
        )}
        <div className="srvbtns">
          <button onClick={save} disabled={busy}>
            {editingId ? "Save changes" : "Add server"}
          </button>
          <button onClick={test} disabled={busy}>
            Test connection
          </button>
          {editingId && (
            <button className="ghost" onClick={reset} disabled={busy}>
              Cancel
            </button>
          )}
          <span className="status">{status}</span>
        </div>
      </div>
      {traffic && (
        <CotTrafficModal
          title={traffic === "*" ? "TAK server CoT traffic" : `CoT traffic · ${traffic}`}
          fetcher={() => api.serverTraffic(traffic === "*" ? undefined : traffic)}
          onClose={() => setTraffic(null)}
        />
      )}
    </section>
  );
}

function DocsPanel() {
  return (
    <section className="card docs">
      <h2>Documentation</h2>
      <p className="hint">
        Reference guides (PDF). They open in a new tab; right-click a card to download. Regenerate
        with <code>python docs/generate_docs.py</code>.
      </p>
      <div className="doc-list">
        {DOCS.map((d) => (
          <a
            key={d.file}
            className="doc-card"
            href={`/docs/${d.file}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            <span className="doc-icon">PDF</span>
            <span className="doc-text">
              <span className="doc-title">{d.title}</span>
              <span className="doc-blurb">{d.blurb}</span>
            </span>
            <span className="doc-open">open →</span>
          </a>
        ))}
      </div>
    </section>
  );
}

function LogsPanel() {
  const [msgs, setMsgs] = useState<MsgLogEntry[]>([]);
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [appLog, setAppLog] = useState<AppLogRecord[]>([]);
  const [dir, setDir] = useState("");
  const [disp, setDisp] = useState("");
  const [selected, setSelected] = useState<MsgLogEntry | null>(null);

  useEffect(() => {
    const load = () => {
      api
        .messageLog(dir, disp)
        .then((r) => {
          setMsgs([...r.entries].reverse());
          setCounts(r.counts);
        })
        .catch(console.error);
      api.appLog().then((r) => setAppLog([...r].reverse())).catch(console.error);
    };
    load();
    const t = setInterval(load, 1500);
    return () => clearInterval(t);
  }, [dir, disp]);

  const hhmmss = (ts: number) => new Date(ts * 1000).toISOString().slice(11, 19);

  return (
    <>
      <section className="card">
        <h2>Application Log</h2>
        <p className="hint">Lifecycle, warnings and errors from the node (newest first).</p>
        <ul className="applog">
          {appLog.length === 0 && <li className="hint">no records</li>}
          {appLog.map((r, i) => (
            <li key={i} className={`lvl-${r.level.toLowerCase()}`}>
              <span className="time">{hhmmss(r.ts)}</span>
              <span className="level">{r.level}</span>
              <span className="lname">{r.logger}</span>
              <span className="lmsg">{r.message}</span>
            </li>
          ))}
        </ul>
      </section>

      <section className="card msglog">
        <h2>Message Log — incoming / outgoing, accepted / rejected</h2>
        <div className="logfilters">
          <label>
            direction{" "}
            <select value={dir} onChange={(e) => setDir(e.target.value)}>
              <option value="">all</option>
              <option value="in">incoming</option>
              <option value="out">outgoing</option>
            </select>
          </label>
          <label>
            disposition{" "}
            <select value={disp} onChange={(e) => setDisp(e.target.value)}>
              <option value="">all</option>
              <option value="accepted">accepted</option>
              <option value="rejected">rejected</option>
            </select>
          </label>
          <span className="hint">
            in {counts.in ?? 0} · out {counts.out ?? 0} · accepted {counts.accepted ?? 0} ·{" "}
            <span style={{ color: "#c0392b" }}>rejected {counts.rejected ?? 0}</span>
          </span>
        </div>
        <div className="loghead">
          <span></span>
          <span>Type</span>
          <span>From</span>
          <span>Disposition / reason</span>
          <span>Time</span>
        </div>
        <ul>
          {msgs.map((e, i) => (
            <li
              key={i}
              className={`${e.disposition} clickable`}
              title="click for full message detail"
              onClick={() => setSelected(e)}
            >
              <span className="dir">{e.direction === "out" ? "▲ TX" : "▼ RX"}</span>
              <span className="type" style={{ color: typeColor(e.type ?? "") }}>
                {e.type ?? "—"}
              </span>
              <span className="from">
                {e.callsign ? `${e.callsign} (${e.originator_id})` : e.originator_id ?? "—"}
              </span>
              <span className="disp">
                {e.disposition === "accepted" ? (
                  <span className="ok">accepted</span>
                ) : (
                  <span className="rej">✗ {e.reason}</span>
                )}
              </span>
              <span className="time">{hhmmss(e.ts)}</span>
            </li>
          ))}
        </ul>
      </section>
      {selected && <MsgLogModal entry={selected} onClose={() => setSelected(null)} />}
    </>
  );
}

function MsgLogModal({ entry, onClose }: { entry: MsgLogEntry; onClose: () => void }) {
  const rows: [string, ReactNode][] = [
    [
      "Type",
      <span style={{ color: typeColor(entry.type ?? "") }}>{entry.type ?? "—"}</span>,
    ],
    ...(bodySidc(entry.body)
      ? ([[
          "Symbol (APP-6D)",
          <span className="sidc-cell">
            <MilSymbol sidc={bodySidc(entry.body)} /> <code>{bodySidc(entry.body)}</code>{" "}
            {sidcValid(bodySidc(entry.body)) ? (
              <span className="ok">✓ 2525D</span>
            ) : (
              <span className="rej">✗ invalid</span>
            )}
          </span>,
        ]] as [string, ReactNode][])
      : []),
    ["Direction", entry.direction === "out" ? "▲ transmitted" : "▼ received"],
    [
      "Disposition",
      entry.disposition === "accepted" ? (
        <span className="ok">accepted</span>
      ) : (
        <span className="rej">✗ rejected — {entry.reason}</span>
      ),
    ],
    [
      "From",
      entry.callsign ? `${entry.callsign} (${entry.originator_id})` : entry.originator_id ?? "—",
    ],
    ["Network", entry.network_id ?? "—"],
    ["Message id", <code>{entry.message_id ?? "—"}</code>],
    ["Sequence", entry.sequence != null ? String(entry.sequence) : "—"],
    ["Reporting time", entry.reporting_time ?? "—"],
    [
      "Classification",
      entry.classification != null ? (
        <span>
          <ClassBadge level={entry.classification} /> {CLASS_LABELS[entry.classification]} ·{" "}
          {entry.releasable_to ?? "—"}
        </span>
      ) : (
        "—"
      ),
    ],
    ["Timestamp", new Date(entry.ts * 1000).toISOString().replace("T", " ").slice(0, 19)],
  ];
  return (
    <Modal
      title={
        <>
          <span style={{ color: typeColor(entry.type ?? "") }}>{entry.type ?? "message"}</span>{" "}
          {entry.direction === "out" ? "▲ TX" : "▼ RX"} · {entry.disposition}
        </>
      }
      onClose={onClose}
    >
      <h3>Envelope</h3>
      <KvTable rows={rows} />
      <h3>Body (JDSSDM)</h3>
      {entry.body ? <StructuredValue value={entry.body} /> : <span className="jnil">— no decoded body —</span>}
      <CopyJson value={entry} />
    </Modal>
  );
}

function SimulationPanel() {
  const [status, setStatus] = useState<SimStatus | null>(null);
  const [interval, setIntervalS] = useState(1);
  const [rogue, setRogue] = useState(false);
  const [isolated, setIsolated] = useState(false);
  const [busy, setBusy] = useState(false);

  const load = () => api.simStatus().then(setStatus).catch(console.error);
  useEffect(() => {
    load();
    const t = setInterval(load, 1500);
    return () => clearInterval(t);
  }, []);

  const start = async () => {
    setBusy(true);
    await api.simStart({ interval, rogue: rogue ? "garbage" : null, isolated });
    await load();
    setBusy(false);
  };
  const stop = async () => {
    setBusy(true);
    await api.simStop();
    await load();
    setBusy(false);
  };

  const running = status?.running ?? false;
  return (
    <section className="card sim">
      <h2>Simulation Control</h2>
      <p className="hint">
        Spawns a roster of JDSS-compliant clients. By default they join <b>this node's own
        network</b>, so the Dashboard, Peers, Matrix and Coalition views come alive.
      </p>

      <div className="sim-row">
        <span className={`dot ${running ? "up" : "down"}`} />
        <b>{running ? "RUNNING" : "stopped"}</b>
        {running && status && (
          <span className="hint">
            {" "}
            · {status.client_count} clients · {status.ticks} ticks · net{" "}
            <b>{status.network_id}</b> · {status.transport}
            {status.rogue ? ` · rogue: ${status.rogue}` : ""}
          </span>
        )}
      </div>

      <div className="sim-controls">
        <label>
          tick interval (s){" "}
          <input
            type="number"
            min={0.1}
            step={0.1}
            value={interval}
            disabled={running}
            onChange={(e) => setIntervalS(Number(e.target.value))}
          />
        </label>
        <label>
          <input
            type="checkbox"
            checked={rogue}
            disabled={running}
            onChange={(e) => setRogue(e.target.checked)}
          />{" "}
          include rogue client
        </label>
        <label>
          <input
            type="checkbox"
            checked={isolated}
            disabled={running}
            onChange={(e) => setIsolated(e.target.checked)}
          />{" "}
          isolated (loopback, separate net)
        </label>
      </div>

      {running ? (
        <button className="danger" disabled={busy} onClick={stop}>
          Stop simulation
        </button>
      ) : (
        <button disabled={busy} onClick={start}>
          Start simulation
        </button>
      )}

      {status && status.clients.length > 0 && (
        <table className="conns" style={{ marginTop: "1rem" }}>
          <tbody>
            {status.clients.map((c) => (
              <tr key={c.node_id}>
                <td>{c.callsign}</td>
                <td>
                  <span className="devtag">{c.device ?? "—"}</span>
                </td>
                <td>{c.role}</td>
                <td className="hint">{c.node_id}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </section>
  );
}

function ConnectionsPanel() {
  const [conn, setConn] = useState<Connections | null>(null);
  const load = () => api.connections().then(setConn).catch(console.error);
  useEffect(() => {
    load();
    const t = setInterval(load, 3000);
    return () => clearInterval(t);
  }, []);
  if (!conn) return <section className="card">Loading connections…</section>;

  const state = (peer: string) =>
    conn.policy.overrides[peer] ?? conn.policy.default_action;
  const act = async (peer: string, action: "allow" | "block" | "reset") => {
    await api.setConnection(peer, action);
    load();
  };

  return (
    <section className="card">
      <h2>Connection Management</h2>
      <p className="hint">
        default: <b>{conn.policy.default_action}</b> · dropped by policy:{" "}
        <b>{conn.dropped_by_policy}</b>
      </p>
      {conn.peers.length === 0 ? (
        <p className="hint">No peers to manage yet.</p>
      ) : (
        <table className="conns">
          <tbody>
            {conn.peers.map((p) => {
              const blocked = state(p.node_id) === "block";
              return (
                <tr key={p.node_id} className={blocked ? "blocked" : ""}>
                  <td>
                    <span className={`dot ${blocked ? "down" : "up"}`} />
                    {p.callsign ?? p.node_id}
                  </td>
                  <td>{blocked ? "BLOCKED" : "accepted"}</td>
                  <td>
                    {blocked ? (
                      <button onClick={() => act(p.node_id, "allow")}>Allow</button>
                    ) : (
                      <button className="danger" onClick={() => act(p.node_id, "block")}>
                        Block
                      </button>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      )}
    </section>
  );
}

function CoalitionPanel() {
  const [pol, setPol] = useState<CoalitionPolicy | null>(null);
  const [peers, setPeers] = useState<Peer[]>([]);
  const load = () => {
    api.coalition().then(setPol).catch(console.error);
    api.peers().then(setPeers).catch(() => {});
  };
  useEffect(() => {
    load();
    const t = setInterval(load, 3000);
    return () => clearInterval(t);
  }, []);
  if (!pol) return <section className="card">Loading coalition policy…</section>;

  const blockedList = Object.entries(pol.overrides)
    .filter(([, v]) => v === "block")
    .map(([p]) => p);
  const act = async (peer: string, action: "allow" | "block" | "reset") => {
    await api.setCoalition(peer, action);
    load();
  };

  return (
    <section className="card">
      <h2>Coalition Policy (gossip-distributed)</h2>
      {!pol.enabled ? (
        <p className="hint">No policy authority configured for this network.</p>
      ) : (
        <>
          <p className="hint">
            authority: <b>{pol.authority_id}</b> · v{pol.version} ·{" "}
            {pol.am_authority ? (
              <span style={{ color: "var(--accent)" }}>you are the AUTHORITY</span>
            ) : (
              <span>read-only (distributed to this node)</span>
            )}{" "}
            · default <b>{pol.default_action}</b> ·{" "}
            {pol.signed ? (
              <span style={{ color: "var(--accent)" }}>🔏 Ed25519-signed</span>
            ) : (
              <span style={{ color: "#d29a2b" }}>unsigned</span>
            )}
          </p>
          <p>
            Network-wide blocked:{" "}
            {blockedList.length ? (
              blockedList.map((p) => (
                <span key={p} className="cbadge" style={{ background: "#c0392b", marginRight: 4 }}>
                  {p}
                </span>
              ))
            ) : (
              <span className="hint">none</span>
            )}
          </p>
          {pol.am_authority && (
            <table className="conns">
              <tbody>
                {peers.map((p) => {
                  const blocked = pol.overrides[p.node_id] === "block";
                  return (
                    <tr key={p.node_id} className={blocked ? "blocked" : ""}>
                      <td>{p.callsign ?? p.node_id}</td>
                      <td>{blocked ? "coalition-BLOCKED" : "allowed"}</td>
                      <td>
                        {blocked ? (
                          <button onClick={() => act(p.node_id, "reset")}>Unblock</button>
                        ) : (
                          <button className="danger" onClick={() => act(p.node_id, "block")}>
                            Block network-wide
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </>
      )}
    </section>
  );
}

function MatrixPanel() {
  const [matrix, setMatrix] = useState<ConnMatrix | null>(null);
  const [mode, setMode] = useState<"live" | "probe">("live");
  const [cell, setCell] = useState<{ obs: string; from: string } | null>(null);
  const [hideInactive, setHideInactive] = useState(true);
  const [filter, setFilter] = useState("");
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback((m: "live" | "probe") => {
    setRefreshing(true);
    (m === "live" ? api.matrix() : api.matrixProbe("garbage"))
      .then(setMatrix)
      .catch(console.error)
      .finally(() => setRefreshing(false));
  }, []);
  useEffect(() => {
    load(mode);
    if (mode === "live") {
      const t = setInterval(() => load("live"), 2500);
      return () => clearInterval(t);
    }
  }, [mode, load]);

  const short = (n: string) => n.replace(/^atak-/, "").replace(/-1$/, "").slice(0, 10);
  // coalition block applies to EVERY row (network-wide); local block only to the local row
  const coalitionBlocks = (from: string): boolean => {
    const c = matrix?.coalition;
    if (!c || !c.enabled) return false;
    return (c.overrides[from] ?? c.default_action) === "block";
  };
  const localBlocks = (obs: string, from: string): boolean => {
    const pol = matrix?.policy;
    if (!pol || obs !== pol.node_id) return false;
    return (pol.overrides[from] ?? pol.default_action) === "block";
  };
  // a specific (observer ← originator) cell blocked by the coalition communication matrix
  const pairBlocks = (obs: string, from: string): boolean =>
    matrix?.coalition?.pairs?.[obs]?.includes(from) ?? false;
  const isBlocked = (obs: string, from: string): boolean =>
    coalitionBlocks(from) || localBlocks(obs, from) || pairBlocks(obs, from);

  const nodes = matrix?.nodes ?? [];
  const val = (o: string, f: string) => matrix?.rows[o]?.[f] ?? 0;
  // a node is "active" if it accepted from anyone or anyone accepted from it (or it's special)
  const active = (n: string) =>
    n === matrix?.policy?.node_id ||
    n === matrix?.rogue_node ||
    nodes.some((m) => m !== n && (val(n, m) > 0 || val(m, n) > 0));
  const visible = nodes.filter(
    (n) =>
      (!filter || n.toLowerCase().includes(filter.toLowerCase())) &&
      (!hideInactive || active(n))
  );
  const rowMax = (o: string) => Math.max(1, ...visible.filter((f) => f !== o).map((f) => val(o, f)));
  const totalAccepted = visible.reduce(
    (a, o) => a + visible.reduce((b, f) => b + (o === f ? 0 : val(o, f)), 0),
    0
  );

  const cellStyle = (obs: string, from: string, v: number): CSSProperties => {
    if (isBlocked(obs, from)) return { color: "#c0392b", fontWeight: 700 };
    if (from === matrix?.rogue_node) return { color: "#c0392b", opacity: v ? 1 : 0.5 };
    if (v > 0) {
      const a = 0.12 + 0.5 * Math.min(1, v / rowMax(obs));
      return { color: "var(--text)", background: `rgba(74,156,109,${a.toFixed(2)})` };
    }
    return { color: "var(--muted)" };
  };

  return (
    <section className="card matrix">
      <div className="matrix-head">
        <h2>Connection Matrix — who accepts whom</h2>
        <div className="matrix-controls">
          <div className="segmented">
            <button className={mode === "live" ? "seg active" : "seg"} onClick={() => setMode("live")}>
              Live · peer-gossip
            </button>
            <button
              className={mode === "probe" ? "seg active" : "seg"}
              onClick={() => setMode("probe")}
            >
              Probe + rogue
            </button>
          </div>
          <label className="inline">
            <input
              type="checkbox"
              checked={hideInactive}
              onChange={(e) => setHideInactive(e.target.checked)}
            />{" "}
            hide inactive
          </label>
          <input
            className="matrix-filter"
            placeholder="filter nodes…"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
          />
          <button onClick={() => load(mode)}>Refresh</button>
          {mode === "live" && (
            <span className={`live-dot ${refreshing ? "pulse" : ""}`} title="live · auto-refresh" />
          )}
        </div>
      </div>

      {!matrix ? (
        <p className="hint">probing…</p>
      ) : (
        <>
          <p className="hint matrix-summary">
            showing <b>{visible.length}</b> of {nodes.length} nodes · {totalAccepted} accepted
            <span className="lg self">– self</span>
            <span className="lg ok">■ accepting</span>
            <span className="lg blk">✗ blocked</span>
            {matrix.rogue_node && <span className="lg rogue">● rogue</span>}
          </p>
          {visible.length === 0 ? (
            <p className="hint">no nodes match the filter.</p>
          ) : (
            <div className="matrix-scroll">
              <table className="matrixgrid">
                <thead>
                  <tr>
                    <th className="corner">obs ← from</th>
                    {visible.map((n) => (
                      <th key={n} title={n} className={n === matrix.rogue_node ? "rogue" : ""}>
                        {short(n)}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {visible.map((obs) => (
                    <tr key={obs}>
                      <td
                        className={`rowhead ${obs === matrix.rogue_node ? "rogue" : ""}`}
                        title={obs}
                      >
                        {short(obs)}
                      </td>
                      {visible.map((from) => {
                        const v = val(obs, from);
                        const self = obs === from;
                        const blocked = !self && isBlocked(obs, from);
                        return (
                          <td
                            key={from}
                            style={self ? { color: "var(--muted)" } : cellStyle(obs, from, v)}
                            className={self ? "self" : "cell-click"}
                            title={
                              self ? "" : `${obs} ← ${from}: ${blocked ? "blocked" : v + " accepted"} — click`
                            }
                            onClick={self ? undefined : () => setCell({ obs, from })}
                          >
                            {self ? "–" : blocked ? "✗" : v || ""}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}
      <p className="hint">
        Cell = messages the row node accepted from the column node. Click a cell to inspect it and
        {matrix?.coalition?.am_authority ? " choose whether that pair may communicate" : " see its status"}.
        {matrix?.coalition?.am_authority ? (
          <b> You are the policy authority — pair blocks distribute to the whole coalition.</b>
        ) : matrix?.coalition?.enabled ? (
          " Only the policy authority can edit the communication matrix."
        ) : (
          " Designate a policy authority to edit the matrix network-wide."
        )}
      </p>
      {matrix && cell && (
        <MatrixCellModal
          matrix={matrix}
          cell={cell}
          onClose={() => setCell(null)}
          onChanged={() => load(mode)}
        />
      )}
    </section>
  );
}

function FeedPanel({ events }: { events: MessageEvent[] }) {
  const [selected, setSelected] = useState<MessageEvent | null>(null);
  return (
    <section className="card feed">
      <h2>Live Message Feed</h2>
      <div className="feedhead">
        <span></span>
        <span>Type</span>
        <span>From</span>
        <span>Class</span>
        <span>Time</span>
      </div>
      <ul>
        {events.map((e) => (
          <li
            key={e.message_id}
            className={`${e.direction} clickable`}
            style={{ borderLeftColor: typeColor(e.type) }}
            title="click to inspect the full message"
            onClick={() => setSelected(e)}
          >
            <span className="dir">{e.direction === "sent" ? "▲ TX" : "▼ RX"}</span>
            <span className="type" style={{ color: typeColor(e.type) }}>
              <MilSymbol sidc={bodySidc(e.body)} size={18} /> {e.type}
            </span>
            <span className="from">
              {e.callsign ? `${e.callsign} (${e.originator_id})` : e.originator_id}
            </span>
            <span className="cls">
              <ClassBadge level={e.classification ?? 0} />
            </span>
            <span className="time">{e.reporting_time?.slice(11, 19)}</span>
          </li>
        ))}
      </ul>
      {selected && <MessageModal event={selected} onClose={() => setSelected(null)} />}
    </section>
  );
}

function StructuredValue({ value }: { value: unknown }) {
  if (value === null || value === undefined || value === "")
    return <span className="jnil">—</span>;
  if (Array.isArray(value)) {
    if (value.length === 0) return <span className="jnil">[ ]</span>;
    return (
      <ol className="jarr">
        {value.map((v, i) => (
          <li key={i}>
            <StructuredValue value={v} />
          </li>
        ))}
      </ol>
    );
  }
  if (typeof value === "object") {
    return (
      <table className="jobj">
        <tbody>
          {Object.entries(value as Record<string, unknown>).map(([k, v]) => (
            <tr key={k}>
              <td className="jk">{k}</td>
              <td>
                <StructuredValue value={v} />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  }
  return <span className="jv">{String(value)}</span>;
}

function Modal({
  title,
  onClose,
  children,
}: {
  title: ReactNode;
  onClose: () => void;
  children: ReactNode;
}) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-head">
          <h2>{title}</h2>
          <button className="modal-x" onClick={onClose}>
            ✕
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

function KvTable({ rows }: { rows: [string, ReactNode][] }) {
  return (
    <table className="kv">
      <tbody>
        {rows.map(([k, v]) => (
          <tr key={k}>
            <td>{k}</td>
            <td>{v}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function CopyJson({ value }: { value: unknown }) {
  return (
    <div className="modal-actions">
      <button onClick={() => navigator.clipboard?.writeText(JSON.stringify(value, null, 2))}>
        copy JSON
      </button>
      <span className="hint">Esc or click outside to close</span>
    </div>
  );
}

function MessageModal({ event, onClose }: { event: MessageEvent; onClose: () => void }) {
  const full = {
    header: {
      type: event.type,
      message_id: event.message_id,
      originator_id: event.originator_id,
      callsign: event.callsign,
      reporting_time: event.reporting_time,
      classification: event.classification,
      releasable_to: event.releasable_to,
    },
    body: event.body,
  };
  const sidc = bodySidc(event.body);
  const headerRows: [string, ReactNode][] = [
    ["Type", <span style={{ color: typeColor(event.type) }}>{event.type}</span>],
    ...(sidc
      ? ([[
          "Symbol (APP-6D)",
          <span className="sidc-cell">
            <MilSymbol sidc={sidc} /> <code>{sidc}</code>{" "}
            {sidcValid(sidc) ? <span className="ok">✓ 2525D</span> : <span className="rej">✗ invalid</span>}
          </span>,
        ]] as [string, ReactNode][])
      : []),
    ["Direction", event.direction === "sent" ? "▲ transmitted" : "▼ received"],
    ["Originator", event.callsign ? `${event.callsign} (${event.originator_id})` : event.originator_id],
    ["Message id", <code>{event.message_id}</code>],
    ["Reporting time", event.reporting_time ?? "—"],
    [
      "Classification",
      <span>
        <ClassBadge level={event.classification ?? 0} />{" "}
        {CLASS_LABELS[event.classification ?? 0]} · {event.releasable_to ?? "—"}
      </span>,
    ],
  ];
  return (
    <Modal
      title={
        <>
          <span style={{ color: typeColor(event.type) }}>{event.type}</span> message
        </>
      }
      onClose={onClose}
    >
      <h3>Header</h3>
      <KvTable rows={headerRows} />
      <h3>Body (JDSSDM)</h3>
      <StructuredValue value={event.body ?? {}} />
      <CopyJson value={full} />
    </Modal>
  );
}

function PeerModal({ peer, onClose }: { peer: Peer; onClose: () => void }) {
  const rows: [string, ReactNode][] = [
    ["Callsign", peer.callsign ?? "—"],
    ["Node id", <code>{peer.node_id}</code>],
    ["Nation", peer.nation ?? "—"],
    ["Unit", peer.unit ?? "—"],
    ["Role", peer.role ?? "—"],
    [
      "Classification",
      <span>
        <ClassBadge level={peer.classification} /> {CLASS_LABELS[peer.classification]} ·{" "}
        {peer.releasable_to}
      </span>,
    ],
    ["Messages", String(peer.messages)],
    ["Last seen", `${peer.seconds_ago}s ago`],
    [
      "Status",
      <span>
        <span className={`dot ${peer.connected ? "up" : "down"}`} />
        {peer.connected ? "connected" : "stale"}
      </span>,
    ],
  ];
  return (
    <Modal title={<>Peer · {peer.callsign ?? peer.node_id}</>} onClose={onClose}>
      <h3>Identity &amp; link</h3>
      <KvTable rows={rows} />
      <CopyJson value={peer} />
    </Modal>
  );
}

function MatrixCellModal({
  matrix,
  cell,
  onClose,
  onChanged,
}: {
  matrix: ConnMatrix;
  cell: { obs: string; from: string };
  onClose: () => void;
  onChanged: () => void;
}) {
  const { obs, from } = cell;
  const [busy, setBusy] = useState(false);
  const count = matrix.rows[obs]?.[from] ?? 0;
  const coalitionBlock =
    matrix.coalition && matrix.coalition.enabled
      ? (matrix.coalition.overrides[from] ?? matrix.coalition.default_action) === "block"
      : false;
  const localBlock =
    matrix.policy && obs === matrix.policy.node_id
      ? (matrix.policy.overrides[from] ?? matrix.policy.default_action) === "block"
      : false;
  const pairBlock = matrix.coalition?.pairs?.[obs]?.includes(from) ?? false;
  const amAuthority = matrix.coalition?.am_authority ?? false;

  let status: ReactNode;
  if (coalitionBlock)
    status = <span style={{ color: "#c0392b" }}>✗ blocked network-wide (column: {from})</span>;
  else if (pairBlock)
    status = <span style={{ color: "#c0392b" }}>✗ this pair blocked ({obs} ✗ {from})</span>;
  else if (localBlock)
    status = <span style={{ color: "#c0392b" }}>✗ blocked locally by {obs}</span>;
  else if (count > 0) status = <span style={{ color: "var(--accent)" }}>accepting traffic</span>;
  else status = <span className="jnil">no traffic accepted</span>;

  const rows: [string, ReactNode][] = [
    ["Observer (accepts)", <code>{obs}</code>],
    ["Originator (from)", <code>{from}</code>],
    ["Messages accepted", String(count)],
    ["Status", status],
  ];

  const setPair = async (action: "block" | "allow") => {
    setBusy(true);
    try {
      await api.setCoalitionPair(obs, from, action);
      onChanged();
    } finally {
      setBusy(false);
    }
  };

  return (
    <Modal title={<>Connection · {obs} ← {from}</>} onClose={onClose}>
      <p className="hint">
        Whether the row node ({obs}) may accept traffic from the column node ({from}).
      </p>
      <KvTable rows={rows} />
      {obs === from ? null : amAuthority ? (
        <div className="modal-actions">
          {pairBlock ? (
            <button disabled={busy} onClick={() => setPair("allow")}>
              Allow {obs} ← {from}
            </button>
          ) : (
            <button className="danger" disabled={busy} onClick={() => setPair("block")}>
              Block {obs} ← {from}
            </button>
          )}
          <span className="hint">distributed to the whole coalition</span>
        </div>
      ) : (
        <p className="hint">
          {matrix.coalition?.enabled
            ? "Only the policy authority can change who may communicate."
            : "No policy authority configured — set one to edit the matrix network-wide."}
        </p>
      )}
    </Modal>
  );
}
